In [8]:
path = r"C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions"
print(path)

C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions


In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk(path):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_1.jpg
C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_10.jpg
C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_11.jpg
C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_12.jpg
C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_2.jpg
C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_3.jpg
C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_4.jpg
C:\

In [9]:
import pandas as pd

# Noktalı virgül ayraçlı CSV dosyasını oku
df = pd.read_csv(
    r"C:\Users\Seyid\Downloads\archive (1)\infant_retinal_database_info.csv", 
    sep=";"
)

# İlk 5 satırı göster
print(df.head())

# Veri seti hakkında genel bilgi
print(df.info())


   ID SEX  GESTATIONAL AGE (GA)  BIRTH WEIGHT (BW)  POSTCONCEPTUAL AGE (PA)  \
0   1   F                    41               2905                     44.0   
1   1   F                    41               2905                     47.0   
2   1   F                    41               2905                     50.0   
3   2   M                    40               4040                     41.0   
4   2   M                    40               4040                     43.0   

   DIAGNOSIS CODE (DG)  PLUS FORM (PF)  DEVICE (D)  SERIE NUMBER (S)  
0                   11               0           1                 1  
1                   11               0           1                 2  
2                   11               0           1                 3  
3                   11               0           1                 1  
4                   11               0           1                 2  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 484 entries, 0 to 483
Data columns (total 9 colum

In [10]:
# Her ID için kaç satır (yani kaç resim) var?
counts = df.groupby("ID")["SERIE NUMBER (S)"].count()

print("Toplam resim sayısı:", counts.sum())   # 6004 çıkmalı
print("Ortalama resim sayısı / bebek:", counts.mean())
print("Maksimum resim sayısı / bebek:", counts.max())


Toplam resim sayısı: 484
Ortalama resim sayısı / bebek: 2.574468085106383
Maksimum resim sayısı / bebek: 16


In [11]:
import os

# Görsellerin bulunduğu klasöre git (dataset yapısına göre değişebilir)
img_dir = r"C:\Users\Seyid\Downloads\archive (1)"

# Tüm dosya sayısını say
all_files = []
for root, dirs, files in os.walk(img_dir):
    for file in files:
        if file.lower().endswith((".jpg", ".png", ".jpeg")):
            all_files.append(os.path.join(root, file))

print("Toplam resim dosyası:", len(all_files))
print("İlk 5 resim örneği:", all_files[:5])


Toplam resim dosyası: 18012
İlk 5 resim örneği: ['C:\\Users\\Seyid\\Downloads\\archive (1)\\images\\images\\001\\01\\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_1.jpg', 'C:\\Users\\Seyid\\Downloads\\archive (1)\\images\\images\\001\\01\\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_10.jpg', 'C:\\Users\\Seyid\\Downloads\\archive (1)\\images\\images\\001\\01\\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_11.jpg', 'C:\\Users\\Seyid\\Downloads\\archive (1)\\images\\images\\001\\01\\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_12.jpg', 'C:\\Users\\Seyid\\Downloads\\archive (1)\\images\\images\\001\\01\\001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_2.jpg']


In [12]:
import pandas as pd
import os

# CSV metadata oku
csv_path = r"C:\Users\Seyid\Downloads\archive (1)\infant_retinal_database_info.csv"
df = pd.read_csv(csv_path, sep=";")

# Görsellerin olduğu klasör
img_dir = r"C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions"

# Dosya listesini al
img_files = os.listdir(img_dir)

# Dosya isimlerinden metadata çıkar
img_data = []
for f in img_files:
    # Örn: 019_M_GA35_BW3050_PA46_DG11_PF0_D1_S03_3.jpg
    parts = f.replace(".jpg","").split("_")
    ID = int(parts[0])
    SEX = parts[1]
    GA = int(parts[2].replace("GA",""))
    BW = int(parts[3].replace("BW",""))
    PA = int(parts[4].replace("PA",""))
    DG = int(parts[5].replace("DG",""))
    PF = int(parts[6].replace("PF",""))
    D  = int(parts[7].replace("D",""))
    S  = int(parts[8].replace("S",""))
    FRAME = int(parts[9])  # aynı seri içindeki frame numarası
    
    img_data.append([ID, SEX, GA, BW, PA, DG, PF, D, S, FRAME, f])

# Görsellerden DataFrame
df_imgs = pd.DataFrame(img_data, columns=[
    "ID","SEX","GA","BW","PA","DG","PF","DEVICE","SERIE","FRAME","FILENAME"
])

# Görselleri metadata ile eşleştir
merged = pd.merge(df_imgs, df, 
                  left_on=["ID","SEX","GA","BW","PA","DG","PF","DEVICE","SERIE"], 
                  right_on=["ID","SEX","GESTATIONAL AGE (GA)","BIRTH WEIGHT (BW)","POSTCONCEPTUAL AGE (PA)",
                            "DIAGNOSIS CODE (DG)","PLUS FORM (PF)","DEVICE (D)","SERIE NUMBER (S)"],
                  how="inner")

print("Toplam eşleşen kayıt:", len(merged))
print(merged.head())


Toplam eşleşen kayıt: 5172
   ID SEX  GA    BW  PA  DG  PF  DEVICE  SERIE  FRAME  \
0   1   F  41  2905  44  11   0       1      1      1   
1   1   F  41  2905  44  11   0       1      1     10   
2   1   F  41  2905  44  11   0       1      1     11   
3   1   F  41  2905  44  11   0       1      1     12   
4   1   F  41  2905  44  11   0       1      1      2   

                                        FILENAME  GESTATIONAL AGE (GA)  \
0   001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_1.jpg                    41   
1  001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_10.jpg                    41   
2  001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_11.jpg                    41   
3  001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_12.jpg                    41   
4   001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_2.jpg                    41   

   BIRTH WEIGHT (BW)  POSTCONCEPTUAL AGE (PA)  DIAGNOSIS CODE (DG)  \
0               2905                     44.0                   11   
1               2905                     44.0

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\2241633397.py:38: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  merged = pd.merge(df_imgs, df,


In [13]:
# PA sütununu int yap
df["POSTCONCEPTUAL AGE (PA)"] = df["POSTCONCEPTUAL AGE (PA)"].astype(int)

# Merge tekrar
merged = pd.merge(
    df_imgs, df, 
    left_on=["ID","SEX","GA","BW","PA","DG","PF","DEVICE","SERIE"], 
    right_on=["ID","SEX","GESTATIONAL AGE (GA)","BIRTH WEIGHT (BW)","POSTCONCEPTUAL AGE (PA)",
              "DIAGNOSIS CODE (DG)","PLUS FORM (PF)","DEVICE (D)","SERIE NUMBER (S)"],
    how="inner"
)

print("Toplam eşleşen kayıt:", len(merged))


Toplam eşleşen kayıt: 5598


In [14]:
# Eşleşen dosyaları al
matched_files = set(merged["FILENAME"])

# Eşleşmeyenleri bul
unmatched_files = [f for f in img_files if f not in matched_files]

print("Eşleşmeyen resim sayısı:", len(unmatched_files))
print("İlk 10 eşleşmeyen örnek:", unmatched_files[:10])


Eşleşmeyen resim sayısı: 406
İlk 10 eşleşmeyen örnek: ['108_F_GA40_BW3320_PA43_DG0_PF0_D2_S01_1.jpg', '108_F_GA40_BW3320_PA43_DG0_PF0_D2_S01_10.jpg', '108_F_GA40_BW3320_PA43_DG0_PF0_D2_S01_11.jpg', '108_F_GA40_BW3320_PA43_DG0_PF0_D2_S01_2.jpg', '108_F_GA40_BW3320_PA43_DG0_PF0_D2_S01_3.jpg', '108_F_GA40_BW3320_PA43_DG0_PF0_D2_S01_4.jpg', '108_F_GA40_BW3320_PA43_DG0_PF0_D2_S01_5.jpg', '108_F_GA40_BW3320_PA43_DG0_PF0_D2_S01_6.jpg', '108_F_GA40_BW3320_PA43_DG0_PF0_D2_S01_7.jpg', '108_F_GA40_BW3320_PA43_DG0_PF0_D2_S01_8.jpg']


In [15]:
# !pip -q install --upgrade torch torchvision scikit-learn

import os, re, random, math, json
import numpy as np
import pandas as pd
from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from torch.cuda.amp import autocast, GradScaler

import torchvision
from torchvision import transforms
from torchvision import models

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report, roc_auc_score

# Reproducibility
def set_seed(seed=42):
    random.seed(seed); np.random.seed(seed)
    torch.manual_seed(seed); torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device


device(type='cuda')

In [16]:
# Yollar
CSV_PATH = r"C:\Users\Seyid\Downloads\archive (1)\infant_retinal_database_info.csv"
IMG_DIR  = r"C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions"

# CSV
df = pd.read_csv(CSV_PATH, sep=";")
# PA float gelebiliyor → int yap
df["POSTCONCEPTUAL AGE (PA)"] = df["POSTCONCEPTUAL AGE (PA)"].astype(int)

# Dosyaları listele
img_files = [f for f in os.listdir(IMG_DIR) if f.lower().endswith((".jpg",".jpeg",".png"))]

# Dosya adı kalıbı: 019_M_GA35_BW3050_PA46_DG11_PF0_D1_S03_3.jpg
pat = re.compile(
    r"^(?P<ID>\d+)_"
    r"(?P<SEX>[MF])_"
    r"GA(?P<GA>\d+)_"
    r"BW(?P<BW>\d+)_"
    r"PA(?P<PA>\d+)_"
    r"DG(?P<DG>-?\d+)_"
    r"PF(?P<PF>-?\d+)_"
    r"D(?P<D>\d+)_"
    r"S(?P<S>\d+)_"
    r"(?P<FRAME>\d+)\.(?:jpg|jpeg|png)$",
    re.IGNORECASE
)

parsed = []
bad_names = []
for f in img_files:
    m = pat.match(f)
    if not m:
        bad_names.append(f); 
        continue
    g = m.groupdict()
    parsed.append({
        "FILENAME": f,
        "ID": int(g["ID"]),
        "SEX": g["SEX"],
        "GA": int(g["GA"]),
        "BW": int(g["BW"]),
        "PA": int(g["PA"]),
        "DG": int(g["DG"]),
        "PF": int(g["PF"]),
        "DEVICE": int(g["D"]),
        "SERIE": int(g["S"]),
        "FRAME": int(g["FRAME"])
    })

df_imgs = pd.DataFrame(parsed)
print("Parse edilen görsel sayısı:", len(df_imgs))
print("Pattern’e uymayan isim sayısı:", len(bad_names))
df_imgs.head()


Parse edilen görsel sayısı: 6004
Pattern’e uymayan isim sayısı: 0


FILENAME  ID SEX  GA    BW  PA  DG  \
0   001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_1.jpg   1   F  41  2905  44  11   
1  001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_10.jpg   1   F  41  2905  44  11   
2  001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_11.jpg   1   F  41  2905  44  11   
3  001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_12.jpg   1   F  41  2905  44  11   
4   001_F_GA41_BW2905_PA44_DG11_PF0_D1_S01_2.jpg   1   F  41  2905  44  11   

   PF  DEVICE  SERIE  FRAME  
0   0       1      1      1  
1   0       1      1     10  
2   0       1      1     11  
3   0       1      1     12  
4   0       1      1      2

In [17]:
# Eşleştirme
merged = pd.merge(
    df_imgs, df,
    left_on=["ID","SEX","GA","BW","PA","DG","PF","DEVICE","SERIE"],
    right_on=["ID","SEX","GESTATIONAL AGE (GA)","BIRTH WEIGHT (BW)","POSTCONCEPTUAL AGE (PA)",
              "DIAGNOSIS CODE (DG)","PLUS FORM (PF)","DEVICE (D)","SERIE NUMBER (S)"],
    how="inner"
)

print("Toplam eşleşen kayıt:", len(merged))

# Kaç dosya eşleşmedi?
matched_files = set(merged["FILENAME"])
unmatched = [f for f in img_files if f not in matched_files]
print("Eşleşmeyen görsel sayısı:", len(unmatched))


Toplam eşleşen kayıt: 5598
Eşleşmeyen görsel sayısı: 406


In [18]:
# Etiket sınıfları
dg_classes = sorted(merged["DIAGNOSIS CODE (DG)"].unique().tolist())
pf_classes = sorted(merged["PLUS FORM (PF)"].unique().tolist())

dg2idx = {c:i for i,c in enumerate(dg_classes)}
pf2idx = {c:i for i,c in enumerate(pf_classes)}

merged["dg_idx"] = merged["DIAGNOSIS CODE (DG)"].map(dg2idx)
merged["pf_idx"] = merged["PLUS FORM (PF)"].map(pf2idx)

# Grup tablosu (sızıntıya karşı aynı serinin tüm frameleri birlikte kalsın)
group_cols = ["ID","DEVICE (D)","SERIE NUMBER (S)"]
grp = (merged
       .groupby(group_cols, as_index=False)
       .agg({
           "FILENAME":"count",
           "dg_idx":"first",
           "pf_idx":"first",
           "DEVICE (D)":"first"
       })
       .rename(columns={"FILENAME":"N"})
      )

# Stratify etiketi: cihaz+PF (gerekirse DG'yi de kat)
grp["strat"] = grp["DEVICE (D)"].astype(str) + "|" + grp["pf_idx"].astype(str)

# Train/Val/Test bölme (grup indeksleri üstünden)
train_grp_idx, test_grp_idx = train_test_split(
    grp.index.values, test_size=0.2, random_state=42, stratify=grp["strat"]
)
# train → train/val
sub = grp.iloc[train_grp_idx]
train_grp_idx2, val_grp_idx = train_test_split(
    sub.index.values, test_size=0.1, random_state=42, stratify=sub["strat"]
)

# Hangi gruplar?
train_groups = set(grp.loc[train_grp_idx2, ["ID","DEVICE (D)","SERIE NUMBER (S)"]].itertuples(index=False, name=None))
val_groups   = set(grp.loc[val_grp_idx,   ["ID","DEVICE (D)","SERIE NUMBER (S)"]].itertuples(index=False, name=None))
test_groups  = set(grp.loc[test_grp_idx,  ["ID","DEVICE (D)","SERIE NUMBER (S)"]].itertuples(index=False, name=None))

def mask_from_groups(dfm, groups):
    keys = list(zip(dfm["ID"], dfm["DEVICE (D)"], dfm["SERIE NUMBER (S)"]))
    return np.array([k in groups for k in keys])

train_mask = mask_from_groups(merged, train_groups)
val_mask   = mask_from_groups(merged, val_groups)
test_mask  = mask_from_groups(merged, test_groups)

train_df = merged[train_mask].reset_index(drop=True)
val_df   = merged[val_mask].reset_index(drop=True)
test_df  = merged[test_mask].reset_index(drop=True)

len(train_df), len(val_df), len(test_df)


(4143, 433, 1022)

In [19]:
IM_SIZE = 224
BATCH_SIZE = 32
NUM_WORKERS = 2

# ImageNet normalization
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

train_tfms = transforms.Compose([
    transforms.RandomResizedCrop(IM_SIZE, scale=(0.8, 1.0)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1, hue=0.05),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

eval_tfms = transforms.Compose([
    transforms.Resize(int(IM_SIZE*1.15)),
    transforms.CenterCrop(IM_SIZE),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

class ROPDataset(Dataset):
    def __init__(self, dfm, img_dir, tfms):
        self.dfm = dfm.copy()
        self.img_dir = img_dir
        self.tfms = tfms

    def __len__(self): return len(self.dfm)

    def __getitem__(self, i):
        row = self.dfm.iloc[i]
        path = os.path.join(self.img_dir, row["FILENAME"])
        with Image.open(path) as img:
            img = img.convert("RGB")
            img = self.tfms(img)
        dg = int(row["dg_idx"])
        pf = int(row["pf_idx"])
        device_id = int(row["DEVICE (D)"])
        return img, dg, pf, device_id

train_ds = ROPDataset(train_df, IMG_DIR, train_tfms)
val_ds   = ROPDataset(val_df,   IMG_DIR, eval_tfms)
test_ds  = ROPDataset(test_df,  IMG_DIR, eval_tfms)

# Sınıf ağırlıkları + Sampler (train)
dg_counts = train_df["dg_idx"].value_counts().sort_index().values
pf_counts = train_df["pf_idx"].value_counts().sort_index().values

dg_w = 1.0 / (dg_counts + 1e-9)
pf_w = 1.0 / (pf_counts + 1e-9)

# Örnek başına ağırlık = DG ve PF ağırlıklarının ortalaması
sample_weights = []
for _, r in train_df.iterrows():
    w = 0.5 * dg_w[r["dg_idx"]] + 0.5 * pf_w[r["pf_idx"]]
    sample_weights.append(w)
sample_weights = torch.DoubleTensor(sample_weights)

sampler = WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, sampler=sampler,
                          num_workers=0, pin_memory=True)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=0, pin_memory=True)
test_loader  = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=0, pin_memory=True)


len(train_ds), len(val_ds), len(test_ds)


(4143, 433, 1022)

In [20]:
num_dg = len(dg_classes)
num_pf = len(pf_classes)

class ROPNet(nn.Module):
    def __init__(self, num_dg, num_pf):
        super().__init__()
        # Pretrained backbone
        try:
            weights = models.EfficientNet_B0_Weights.IMAGENET1K_V1
            base = models.efficientnet_b0(weights=weights)
            feat_dim = base.classifier[1].in_features
        except:
            base = models.efficientnet_b0(pretrained=True)
            feat_dim = base.classifier[1].in_features

        self.backbone = base.features
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.dropout = nn.Dropout(0.2)
        self.dg_head = nn.Linear(feat_dim, num_dg)
        self.pf_head = nn.Linear(feat_dim, num_pf)

    def forward(self, x):
        x = self.backbone(x)
        x = self.pool(x).flatten(1)
        x = self.dropout(x)
        dg_logits = self.dg_head(x)
        pf_logits = self.pf_head(x)
        return dg_logits, pf_logits

model = ROPNet(num_dg, num_pf).to(device)

# Class weights (opsiyonel, sampler zaten var; yine de ekleyebiliriz)
dg_class_weights = torch.tensor(dg_w, dtype=torch.float32, device=device)
pf_class_weights = torch.tensor(pf_w, dtype=torch.float32, device=device)

loss_dg = nn.CrossEntropyLoss(weight=dg_class_weights)
loss_pf = nn.CrossEntropyLoss(weight=pf_class_weights)

optimizer = torch.optim.AdamW(model.parameters(), lr=2e-4, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=10)
scaler = GradScaler()


C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\1222629442.py:41: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()


In [21]:
# 🔹 IMPORTLAR
import torch
import torch.nn as nn
import torch.optim as optim
from torch.cuda.amp import autocast, GradScaler
from torch.utils.data import DataLoader, Dataset
import numpy as np
from sklearn.metrics import accuracy_score, f1_score
from tqdm.notebook import tqdm

# 🔹 DEVICE
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 🔹 MODEL, LOSS, OPTIMIZER, SCALER, SCHEDULER (örnek)
model = model  # kendi modelini buraya koy
model.to(device)

loss_dg = nn.CrossEntropyLoss()
loss_pf = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr=1e-4)
scaler = GradScaler()
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=0.95)

# 🔹 DATA LOADERS
# train_loader ve val_loader önceden tanımlanmalı
# Örnek:
# train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
# val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

# 🔹 EKSTRA BİLGİLER
dg_classes = ["class0", "class1"]    # örnek
pf_classes = ["class0", "class1", "class2"]
dg2idx = {c:i for i,c in enumerate(dg_classes)}
pf2idx = {c:i for i,c in enumerate(pf_classes)}
IM_SIZE = (224,224)

# 🔹 RUN EPOCH FONKSİYONU
def run_epoch(loader, model, optimizer=None, scaler=None):
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    total_loss = 0.0
    all_dg_true, all_dg_pred = [], []
    all_pf_true, all_pf_pred = [], []

    for imgs, dg, pf, dev in tqdm(loader, desc="Batches"):
        imgs = imgs.to(device, non_blocking=True)
        dg = dg.to(device, non_blocking=True)
        pf = pf.to(device, non_blocking=True)

        with autocast(enabled=True):
            dg_logits, pf_logits = model(imgs)
            ldg = loss_dg(dg_logits, dg)
            lpf = loss_pf(pf_logits, pf)
            loss = ldg + lpf

        if is_train:
            optimizer.zero_grad(set_to_none=True)
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()

        total_loss += loss.item() * imgs.size(0)

        # preds
        dg_pred = torch.argmax(dg_logits, dim=1)
        pf_pred = torch.argmax(pf_logits, dim=1)

        all_dg_true.extend(dg.detach().cpu().numpy().tolist())
        all_dg_pred.extend(dg_pred.detach().cpu().numpy().tolist())
        all_pf_true.extend(pf.detach().cpu().numpy().tolist())
        all_pf_pred.extend(pf_pred.detach().cpu().numpy().tolist())

    n = len(loader.dataset)
    avg_loss = total_loss / max(n,1)

    dg_acc = accuracy_score(all_dg_true, all_dg_pred)
    pf_acc = accuracy_score(all_pf_true, all_pf_pred)
    dg_f1  = f1_score(all_dg_true, all_dg_pred, average="macro")
    pf_f1  = f1_score(all_pf_true, all_pf_pred, average="macro")

    return {
        "loss": avg_loss,
        "dg_acc": dg_acc, "dg_f1": dg_f1,
        "pf_acc": pf_acc, "pf_f1": pf_f1,
        "dg_true": np.array(all_dg_true), "dg_pred": np.array(all_dg_pred),
        "pf_true": np.array(all_pf_true), "pf_pred": np.array(all_pf_pred),
    }

# 🔹 EĞİTİM DÖNGÜSÜ
EPOCHS = 10
best_val = None
best_path = "rop_multitask_efficientnet_b0.pt"

for epoch in range(1, EPOCHS+1):
    print(f"\n=== Epoch {epoch} ===", flush=True)
    
    # Train
    tr = run_epoch(train_loader, model, optimizer, scaler)

    # Validation
    with torch.no_grad():
        va = run_epoch(val_loader, model, optimizer=None)

    # Scheduler step
    scheduler.step()

    # Epoch özeti
    print(f"Train Loss {tr['loss']:.4f} | DG acc {tr['dg_acc']:.3f} f1 {tr['dg_f1']:.3f} | "
          f"PF acc {tr['pf_acc']:.3f} f1 {tr['pf_f1']:.3f}", flush=True)
    print(f"Val Loss {va['loss']:.4f} | DG acc {va['dg_acc']:.3f} f1 {va['dg_f1']:.3f} | "
          f"PF acc {va['pf_acc']:.3f} f1 {va['pf_f1']:.3f}", flush=True)

    # En iyi modeli kaydet
    score = va["dg_f1"] + va["pf_f1"]
    if (best_val is None) or (score > best_val):
        best_val = score
        torch.save({
            "model_state": model.state_dict(),
            "dg_classes": dg_classes,
            "pf_classes": pf_classes,
            "dg2idx": dg2idx, "pf2idx": pf2idx,
            "img_size": IM_SIZE
        }, best_path)
        print(f"✅ En iyi model kaydedildi → {best_path}", flush=True)



=== Epoch 1 ===


C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:22: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler = GradScaler()


Batches:   0%|          | 0/130 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Batches:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Train Loss 1.9454 | DG acc 0.518 f1 0.500 | PF acc 0.889 f1 0.811
Val Loss 1.6011 | DG acc 0.533 f1 0.232 | PF acc 0.972 f1 0.899
✅ En iyi model kaydedildi → rop_multitask_efficientnet_b0.pt

=== Epoch 2 ===


Batches:   0%|          | 0/130 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Batches:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Train Loss 0.8948 | DG acc 0.748 f1 0.741 | PF acc 0.969 f1 0.948
Val Loss 1.3959 | DG acc 0.644 f1 0.371 | PF acc 0.965 f1 0.882
✅ En iyi model kaydedildi → rop_multitask_efficientnet_b0.pt

=== Epoch 3 ===


Batches:   0%|          | 0/130 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Batches:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Train Loss 0.5589 | DG acc 0.838 f1 0.838 | PF acc 0.986 f1 0.975
Val Loss 1.3080 | DG acc 0.677 f1 0.397 | PF acc 0.972 f1 0.899
✅ En iyi model kaydedildi → rop_multitask_efficientnet_b0.pt

=== Epoch 4 ===


Batches:   0%|          | 0/130 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Batches:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Train Loss 0.3960 | DG acc 0.878 f1 0.881 | PF acc 0.992 f1 0.987
Val Loss 1.3182 | DG acc 0.663 f1 0.373 | PF acc 0.979 f1 0.929
✅ En iyi model kaydedildi → rop_multitask_efficientnet_b0.pt

=== Epoch 5 ===


Batches:   0%|          | 0/130 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Batches:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Train Loss 0.3307 | DG acc 0.898 f1 0.901 | PF acc 0.993 f1 0.988
Val Loss 1.2775 | DG acc 0.700 f1 0.346 | PF acc 0.972 f1 0.902

=== Epoch 6 ===


Batches:   0%|          | 0/130 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Batches:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Train Loss 0.2692 | DG acc 0.920 f1 0.921 | PF acc 0.994 f1 0.990
Val Loss 1.2926 | DG acc 0.711 f1 0.415 | PF acc 0.968 f1 0.888
✅ En iyi model kaydedildi → rop_multitask_efficientnet_b0.pt

=== Epoch 7 ===


Batches:   0%|          | 0/130 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Batches:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Train Loss 0.2335 | DG acc 0.928 f1 0.931 | PF acc 0.994 f1 0.990
Val Loss 1.2988 | DG acc 0.718 f1 0.429 | PF acc 0.972 f1 0.902
✅ En iyi model kaydedildi → rop_multitask_efficientnet_b0.pt

=== Epoch 8 ===


Batches:   0%|          | 0/130 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Batches:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Train Loss 0.1986 | DG acc 0.942 f1 0.944 | PF acc 0.996 f1 0.993
Val Loss 1.3340 | DG acc 0.702 f1 0.423 | PF acc 0.970 f1 0.895

=== Epoch 9 ===


Batches:   0%|          | 0/130 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Batches:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Train Loss 0.1697 | DG acc 0.951 f1 0.953 | PF acc 0.997 f1 0.995
Val Loss 1.3175 | DG acc 0.739 f1 0.460 | PF acc 0.968 f1 0.888
✅ En iyi model kaydedildi → rop_multitask_efficientnet_b0.pt

=== Epoch 10 ===


Batches:   0%|          | 0/130 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Batches:   0%|          | 0/14 [00:00<?, ?it/s]

C:\Users\Seyid\AppData\Local\Temp\ipykernel_11904\3405241621.py:52: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast(enabled=True):


Train Loss 0.1534 | DG acc 0.956 f1 0.958 | PF acc 0.998 f1 0.996
Val Loss 1.3424 | DG acc 0.751 f1 0.459 | PF acc 0.972 f1 0.904
✅ En iyi model kaydedildi → rop_multitask_efficientnet_b0.pt


In [22]:
# En iyi modeli yükle
ckpt = torch.load(best_path, map_location=device)
model.load_state_dict(ckpt["model_state"])
model.eval()

# Testte tahmin + olasılık (ROC için)
all_dg_true, all_dg_pred = [], []
all_pf_true, all_pf_pred = [], []
all_pf_proba = []  # softmax

all_device = []

with torch.no_grad():
    for imgs, dg, pf, dev in test_loader:
        imgs = imgs.to(device, non_blocking=True)
        dg = dg.to(device, non_blocking=True)
        pf = pf.to(device, non_blocking=True)

        dg_logits, pf_logits = model(imgs)

        dg_pred = torch.argmax(dg_logits, dim=1)
        pf_pred = torch.argmax(pf_logits, dim=1)

        pf_prob = torch.softmax(pf_logits, dim=1)

        all_dg_true.extend(dg.cpu().numpy().tolist())
        all_dg_pred.extend(dg_pred.cpu().numpy().tolist())
        all_pf_true.extend(pf.cpu().numpy().tolist())
        all_pf_pred.extend(pf_pred.cpu().numpy().tolist())
        all_pf_proba.append(pf_prob.cpu().numpy())

        all_device.extend(dev.numpy().tolist())

all_pf_proba = np.concatenate(all_pf_proba, axis=0)

# Skorlar
print("=== TEST METRİKLERİ ===")
print("DG Accuracy:", accuracy_score(all_dg_true, all_dg_pred))
print("DG Macro-F1:", f1_score(all_dg_true, all_dg_pred, average="macro"))
print("PF Accuracy:", accuracy_score(all_pf_true, all_pf_pred))
print("PF Macro-F1:", f1_score(all_pf_true, all_pf_pred, average="macro"))

# Confusion matrices
print("\nDG Confusion Matrix:\n", confusion_matrix(all_dg_true, all_dg_pred, labels=list(range(num_dg))))
print("\nPF Confusion Matrix:\n", confusion_matrix(all_pf_true, all_pf_pred, labels=list(range(num_pf))))

# ROC AUC (PF)
try:
    if num_pf == 2:
        # binary: pozitif sınıfı 1 kabul ediyoruz (idx=1)
        pf_auc = roc_auc_score(all_pf_true, all_pf_proba[:,1])
    else:
        pf_auc = roc_auc_score(all_pf_true, all_pf_proba, multi_class="ovr", average="macro")
    print("\nPF ROC AUC:", pf_auc)
except Exception as e:
    print("\nPF ROC AUC hesaplanamadı:", e)

# Cihazlara göre performans
all_dg_true = np.array(all_dg_true); all_dg_pred = np.array(all_dg_pred)
all_pf_true = np.array(all_pf_true); all_pf_pred = np.array(all_pf_pred)
all_device  = np.array(all_device)

print("\n=== Cihaz Bazlı Metri̇kler ===")
for d in sorted(np.unique(all_device).tolist()):
    m = all_device == d
    dg_acc_d = accuracy_score(all_dg_true[m], all_dg_pred[m])
    pf_acc_d = accuracy_score(all_pf_true[m], all_pf_pred[m])
    print(f"D{d}: DG acc={dg_acc_d:.3f} | PF acc={pf_acc_d:.3f} | N={m.sum()}")


=== TEST METRİKLERİ ===
DG Accuracy: 0.7035225048923679
DG Macro-F1: 0.5678049046884548
PF Accuracy: 0.9863013698630136
PF Macro-F1: 0.9573557463042441

DG Confusion Matrix:
 [[379   0  11  10   0   0  30   0  56   4   0]
 [  0   0  12   0   0   0   0   0   3   0   0]
 [  6   0   1  21   0   1   3   0   3   1   0]
 [  7   0  16  41   0   0  12   0   2   0   0]
 [  0   0   0   4  40   0   0   0   6   0   0]
 [  0   0   0   0   0  44   0   0   0   0   0]
 [ 46   0   3   2   0   0  42   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0]
 [ 17   0   0   2   0   2  12   0 149   2   0]
 [  5   0   1   0   0   0   0   0   0   4   0]
 [  1   0   0   0   0   0   0   0   2   0  19]]

PF Confusion Matrix:
 [[925   8]
 [  6  83]]

PF ROC AUC: 0.9978082059804666

=== Cihaz Bazlı Metri̇kler ===
D1: DG acc=0.666 | PF acc=0.993 | N=407
D2: DG acc=0.777 | PF acc=0.977 | N=484
D3: DG acc=0.550 | PF acc=1.000 | N=131


In [23]:
# Zaten /kaggle/working içinde best model kaydedildi.
# İnference örneği (tek görsel):
from torchvision.transforms.functional import to_tensor, normalize, resize, center_crop

def predict_image(img_path):
    model.eval()
    with Image.open(img_path) as img:
        img = img.convert("RGB")
        # eval tfms ile aynı
        img = transforms.Resize(int(IM_SIZE*1.15))(img)
        img = transforms.CenterCrop(IM_SIZE)(img)
        x = transforms.ToTensor()(img)
        x = transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD)(x)
        x = x.unsqueeze(0).to(device)

    with torch.no_grad():
        dg_logits, pf_logits = model(x)
        dg_prob = torch.softmax(dg_logits, dim=1)[0].cpu().numpy()
        pf_prob = torch.softmax(pf_logits, dim=1)[0].cpu().numpy()

    dg_idx_pred = int(dg_prob.argmax())
    pf_idx_pred = int(pf_prob.argmax())

    dg_label = dg_classes[dg_idx_pred]
    pf_label = pf_classes[pf_idx_pred]

    return {
        "DG_pred": int(dg_label), "DG_proba": dg_prob.tolist(),
        "PF_pred": int(pf_label), "PF_proba": pf_prob.tolist()
    }

# Örnek kullanım:
# sample_path = os.path.join(IMG_DIR, merged.iloc[0]["FILENAME"])
# predict_image(sample_path)


In [24]:
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report, roc_auc_score
import torch

# Modeli yükle ve eval moduna al
ckpt = torch.load("rop_multitask_efficientnet_b0.pt", map_location=device)
model.load_state_dict(ckpt["model_state"])
model.eval()

all_dg_true, all_dg_pred = [], []
all_pf_true, all_pf_pred = [], []
all_pf_proba = []
all_device = []

with torch.no_grad():
    for imgs, dg, pf, dev in test_loader:
        imgs = imgs.to(device)
        dg = dg.to(device)
        pf = pf.to(device)

        dg_logits, pf_logits = model(imgs)

        dg_pred = torch.argmax(dg_logits, dim=1)
        pf_pred = torch.argmax(pf_logits, dim=1)

        pf_prob = torch.softmax(pf_logits, dim=1)

        all_dg_true.extend(dg.cpu().numpy().tolist())
        all_dg_pred.extend(dg_pred.cpu().numpy().tolist())
        all_pf_true.extend(pf.cpu().numpy().tolist())
        all_pf_pred.extend(pf_pred.cpu().numpy().tolist())
        all_pf_proba.append(pf_prob.cpu().numpy())
        all_device.extend(dev.numpy().tolist())

all_pf_proba = np.concatenate(all_pf_proba, axis=0)
all_dg_true = np.array(all_dg_true); all_dg_pred = np.array(all_dg_pred)
all_pf_true = np.array(all_pf_true); all_pf_pred = np.array(all_pf_pred)
all_device = np.array(all_device)

# DG metrikleri
dg_acc = accuracy_score(all_dg_true, all_dg_pred)
dg_f1  = f1_score(all_dg_true, all_dg_pred, average="macro")
print("=== DG METRİKLERİ ===")
print("Accuracy:", dg_acc)
print("Macro-F1:", dg_f1)
print("Confusion Matrix:\n", confusion_matrix(all_dg_true, all_dg_pred))
print("Classification Report:\n", classification_report(all_dg_true, all_dg_pred))

# PF metrikleri
pf_acc = accuracy_score(all_pf_true, all_pf_pred)
pf_f1  = f1_score(all_pf_true, all_pf_pred, average="macro")
print("\n=== PF METRİKLERİ ===")
print("Accuracy:", pf_acc)
print("Macro-F1:", pf_f1)
print("Confusion Matrix:\n", confusion_matrix(all_pf_true, all_pf_pred))
print("Classification Report:\n", classification_report(all_pf_true, all_pf_pred))

# PF ROC AUC
try:
    if len(pf_classes) == 2:
        pf_auc = roc_auc_score(all_pf_true, all_pf_proba[:,1])
    else:
        pf_auc = roc_auc_score(all_pf_true, all_pf_proba, multi_class="ovr", average="macro")
    print("PF ROC AUC:", pf_auc)
except Exception as e:
    print("PF ROC AUC hesaplanamadı:", e)

# Cihaz bazlı performans
print("\n=== CİHAZ BAZLI METRİKLER ===")
for d in sorted(np.unique(all_device)):
    mask = all_device == d
    dg_acc_d = accuracy_score(all_dg_true[mask], all_dg_pred[mask])
    pf_acc_d = accuracy_score(all_pf_true[mask], all_pf_pred[mask])
    print(f"D{d}: DG acc={dg_acc_d:.3f} | PF acc={pf_acc_d:.3f} | N={mask.sum()}")


=== DG METRİKLERİ ===
Accuracy: 0.7035225048923679
Macro-F1: 0.5678049046884548
Confusion Matrix:
 [[379   0  11  10   0   0  30  56   4   0]
 [  0   0  12   0   0   0   0   3   0   0]
 [  6   0   1  21   0   1   3   3   1   0]
 [  7   0  16  41   0   0  12   2   0   0]
 [  0   0   0   4  40   0   0   6   0   0]
 [  0   0   0   0   0  44   0   0   0   0]
 [ 46   0   3   2   0   0  42   0   0   0]
 [ 17   0   0   2   0   2  12 149   2   0]
 [  5   0   1   0   0   0   0   0   4   0]
 [  1   0   0   0   0   0   0   2   0  19]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.77      0.80       490
           1       0.00      0.00      0.00        15
           2       0.02      0.03      0.03        36
           3       0.51      0.53      0.52        78
           4       1.00      0.80      0.89        50
           5       0.94      1.00      0.97        44
           6       0.42      0.45      0.44        93
           8 

C:\Users\Seyid\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Seyid\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Seyid\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [25]:
from PIL import Image
from torchvision import transforms

# 0️⃣ Cihazı ayarla
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

# 1️⃣ Resmi yükle ve ön işle
img_path = r"C:\Users\Seyid\Downloads\archive (1)\images_stack_without_captions\images_stack_without_captions\188_F_GA28_BW1070_PA35_DG0_PF0_D3_S02_9.jpg"  # Buraya kendi resminin yolunu yaz
img = Image.open(img_path).convert("RGB")

transform = transforms.Compose([
    transforms.Resize((224, 224)),      # EfficientNet B0 için uygun boyut
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

img = transform(img).unsqueeze(0).to(device)  # batch boyutu ekle

# 2️⃣ Model tahmini
with torch.no_grad():
    dg_logits, pf_logits = model(img)
    dg_pred = torch.argmax(dg_logits, dim=1).item()
    pf_pred = torch.argmax(pf_logits, dim=1).item()
    pf_prob = torch.softmax(pf_logits, dim=1).cpu().numpy()[0]

# 3️⃣ Sonuçları yazdır
print(f"Tahmin DG: {dg_pred}")
print(f"Tahmin PF: {pf_pred}")
print(f"PF olasılıkları: {pf_prob}")


Tahmin DG: 0
Tahmin PF: 0
PF olasılıkları: [9.9998116e-01 1.8857087e-05]
